### ISSUE TITLE
[PROD] There are no applets on account after logging in to the app and website

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-backend#1283]
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/2f2045ca-5361-4cbe-b07a-770538ab4d0c)

Environment:
https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/
Win 10 / Chrome 103
ML v0.19.42 staging
jeraka1732@wodeda.com	1234567890
jeligi9407@zneep.com	123456

https:/admin.mindlogger.org/
https://web.mindlogger.org/
geria.test@gmail.com	123456
anita_ml@protonmail.com	qwe123!!!
bruce_ml@protonmail.com	12345678
bernard_ml@protonmail.com	qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/49e0f95e-ace6-4d5c-b78f-792c1d7eb715)

Environment:
https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/
Win 10 / Chrome 103
ML v0.19.42 staging
jeraka1732@wodeda.com 1234567890
jeligi9407@zneep.com 123456

**Comment by natalia-muzyka** [comment]
the issue is reproducible for an account:
flanker_test@mail.com / 123456

ML v0.21.48 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11

**Comment by natalia-muzyka** [comment]
Fixed on flanker_test@mail.com / 123456
Reproducible on user-stg@ml.com / 123456

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/be11ee66-c9fc-4c05-b7bd-4dd30771b5dd)

Environment:
ML v0.21.48 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11

**Comment by natalia-muzyka** [comment]
Website is blocked:
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-web/533

On mobile app issue is still reproducible on some accounts:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/ee38f547-fc79-498d-8b6e-782402d9b4c4)

Environment:
ML v0.21.48 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
usr2-stg@ml.com / 123456
ml3_general_acc@protonmail.com / 12345678

**Comment by natalia-muzyka** [comment]
Verified as fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/58c798e4-0abd-444c-832d-08d14c6c1ef3)

**Comment by natalia-muzyka** [comment]
The issue is reproducible again on:
https:/admin.mindlogger.org/
https://web.mindlogger.org/
ML v0.21.48 
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
anita_ml@protonmail.com qwe123!!!

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/538b7083-96d8-4779-b503-a3c04885a391)

**Comment by natalia-muzyka** [comment]
The issue is reproducible on one of the legacy staging accounts:
geria2.test@gmail.com	/ McgzF127

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/1f6f5483-8282-4529-9389-0b16c21b6b53)


https:/admin.mindlogger.org/
https://web-staging.mindlogger.org/
ML v0.21.54 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11

**Comment by anq83** [comment]
After login:

![image.png](https://images.zenhubusercontent.com/6316373a3fb7f6df366b544d/285771ee-9a88-4629-b009-88bb9ce26fbb)

**Comment by anq83** [comment]
![image.png](https://images.zenhubusercontent.com/6316373a3fb7f6df366b544d/a40d8dfc-dd56-46af-a776-ce503bf7b41a)

**Comment by anq83** [comment]
"{"@id":"dbt_daily_schema","@type":["reprolib:schemas/Activity"],"http://www.w3.org/2004/02/skos/core#altLabel":[{"@language":"en","@value":"dbt_daily_schema"}],"http://www.w3.org/2004/02/skos/core#prefLabel":[{"@language":"en","@value":"Daily Diary Card"}],"reprolib:terms/addProperties":[{"reprolib:terms/isAbout":[{"@id":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/items/emotions_instructions"}],"reprolib:terms/isVis":[{"@value":true}],"reprolib:terms/variableName":[{"@language":"en","@value":"emotions_instructions"}]},{"reprolib:terms/isAbout":[{"@id":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/items/happiness"}],"reprolib:terms/isVis":[{"@value":true}],"reprolib:terms/variableName":[{"@language":"en","@value":"happiness"}]},{"reprolib:terms/isAbout":[{"@id":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/items/sadness"}],"reprolib:terms/isVis":[{"@value":true}],"reprolib:terms/variableName":[{"@language":"en","@value":"sadness"}]},{"reprolib:terms/isAbout":[{"@id":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/items/anxiety_fear"}],"reprolib:terms/isVis":[{"@value":true}],"reprolib:terms/variableName":[{"@language":"en","@value":"anxiety_fear"}]},{"reprolib:terms/isAbout":[{"@id":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/items/anger"}],"reprolib:terms/isVis":[{"@value":true}],"reprolib:terms/variableName":[{"@language":"en","@value":"anger"}]},{"reprolib:terms/isAbout":[{"@id":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/items/shame_guilt"}],"reprolib:terms/isVis":[{"@value":true}],"reprolib:terms/variableName":[{"@language":"en","@value":"shame_guilt"}]},{"reprolib:terms/isAbout":[{"@id":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/items/target_behaviors_instructions"}],"reprolib:terms/isVis":[{"@value":true}],"reprolib:terms/variableName":[{"@language":"en","@value":"target_behaviors_instructions"}]},{"reprolib:terms/isAbout":[{"@id":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/items/suicide_urges"}],"reprolib:terms/isVis":[{"@value":true}],"reprolib:terms/variableName":[{"@language":"en","@value":"suicide_urges"}]},{"reprolib:terms/isAbout":[{"@id":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/items/suicide_act"}],"reprolib:terms/isVis":[{"@value":true}],"reprolib:terms/variableName":[{"@language":"en","@value":"suicide_act"}]},{"reprolib:terms/isAbout":[{"@id":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/items/self_harm_urges"}],"reprolib:terms/isVis":[{"@value":true}],"reprolib:terms/variableName":[{"@language":"en","@value":"self_harm_urges"}]},{"reprolib:terms/isAbout":[{"@id":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/items/self_harm_act"}],"reprolib:terms/isVis":[{"@value":true}],"reprolib:terms/variableName":[{"@language":"en","@value":"self_harm_act"}]},{"reprolib:terms/isAbout":[{"@id":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/items/impulsive_urges"}],"reprolib:terms/isVis":[{"@value":true}],"reprolib:terms/variableName":[{"@language":"en","@value":"impulsive_urges"}]},{"reprolib:terms/isAbout":[{"@id":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/items/impulsive_urges_act"}],"reprolib:terms/isVis":[{"@value":true}],"reprolib:terms/variableName":[{"@language":"en","@value":"impulsive_urges_act"}]},{"reprolib:terms/isAbout":[{"@id":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/items/picking_scratching_urges"}],"reprolib:terms/isVis":[{"@value":true}],"reprolib:terms/variableName":[{"@language":"en","@value":"picking_scratching_urges"}]},{"reprolib:terms/isAbout":[{"@id":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/items/picking_scratching_act"}],"reprolib:terms/isVis":[{"@value":true}],"reprolib:terms/variableName":[{"@language":"en","@value":"picking_scratching_act"}]},{"reprolib:terms/isAbout":[{"@id":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/items/planning_suicide_urges"}],"reprolib:terms/isVis":[{"@value":true}],"reprolib:terms/variableName":[{"@language":"en","@value":"planning_suicide_urges"}]},{"reprolib:terms/isAbout":[{"@id":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/items/planning_suicide_act"}],"reprolib:terms/isVis":[{"@value":true}],"reprolib:terms/variableName":[{"@language":"en","@value":"planning_suicide_act"}]},{"reprolib:terms/isAbout":[{"@id":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/items/purging_urges"}],"reprolib:terms/isVis":[{"@value":true}],"reprolib:terms/variableName":[{"@language":"en","@value":"purging_urges"}]},{"reprolib:terms/isAbout":[{"@id":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/items/purging_act"}],"reprolib:terms/isVis":[{"@value":true}],"reprolib:terms/variableName":[{"@language":"en","@value":"purging_act"}]},{"reprolib:terms/isAbout":[{"@id":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/items/mindfulness_skills"}],"reprolib:terms/isVis":[{"@value":true}],"reprolib:terms/variableName":[{"@language":"en","@value":"mindfulness_skills"}]},{"reprolib:terms/isAbout":[{"@id":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/items/interpersonal_skills"}],"reprolib:terms/isVis":[{"@value":true}],"reprolib:terms/variableName":[{"@language":"en","@value":"interpersonal_skills"}]},{"reprolib:terms/isAbout":[{"@id":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/items/emotion_regulation"}],"reprolib:terms/isVis":[{"@value":true}],"reprolib:terms/variableName":[{"@language":"en","@value":"emotion_regulation"}]},{"reprolib:terms/isAbout":[{"@id":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/items/distress_tolerance"}],"reprolib:terms/isVis":[{"@value":true}],"reprolib:terms/variableName":[{"@language":"en","@value":"distress_tolerance"}]}],"reprolib:terms/order":[{"@list":[{"@id":"6256ff4f3646a059f4f05f4f/6256ff503646a059f4f05f50"},{"@id":"6256ff4f3646a059f4f05f4f/6256ff513646a059f4f05f52"},{"@id":"6256ff4f3646a059f4f05f4f/6256ff523646a059f4f05f54"},{"@id":"6256ff4f3646a059f4f05f4f/6256ff523646a059f4f05f56"},{"@id":"6256ff4f3646a059f4f05f4f/6256ff533646a059f4f05f58"},{"@id":"6256ff4f3646a059f4f05f4f/6256ff543646a059f4f05f5a"},{"@id":"6256ff4f3646a059f4f05f4f/6256ff553646a059f4f05f5c"},{"@id":"6256ff4f3646a059f4f05f4f/6256ff563646a059f4f05f5e"},{"@id":"6256ff4f3646a059f4f05f4f/6256ff573646a059f4f05f60"},{"@id":"6256ff4f3646a059f4f05f4f/6256ff583646a059f4f05f62"},{"@id":"6256ff4f3646a059f4f05f4f/6256ff593646a059f4f05f64"},{"@id":"6256ff4f3646a059f4f05f4f/6256ff5a3646a059f4f05f66"},{"@id":"6256ff4f3646a059f4f05f4f/6256ff5b3646a059f4f05f68"},{"@id":"6256ff4f3646a059f4f05f4f/6256ff5b3646a059f4f05f6a"},{"@id":"6256ff4f3646a059f4f05f4f/6256ff5c3646a059f4f05f6c"},{"@id":"6256ff4f3646a059f4f05f4f/6256ff5d3646a059f4f05f6e"},{"@id":"6256ff4f3646a059f4f05f4f/6256ff5e3646a059f4f05f70"},{"@id":"6256ff4f3646a059f4f05f4f/6256ff603646a059f4f05f72"},{"@id":"6256ff4f3646a059f4f05f4f/6256ff603646a059f4f05f74"},{"@id":"6256ff4f3646a059f4f05f4f/6256ff613646a059f4f05f76"},{"@id":"6256ff4f3646a059f4f05f4f/6256ff623646a059f4f05f78"},{"@id":"6256ff4f3646a059f4f05f4f/6256ff633646a059f4f05f7a"},{"@id":"6256ff4f3646a059f4f05f4f/6256ff643646a059f4f05f7c"}]}],"reprolib:terms/shuffle":[{"@type":"http://schema.org/Boolean","@value":false}],"schema:description":[{"@language":"en","@value":"Record your emotions, target behaviors, and DBT skills used for today"}],"schema:schemaVersion":[{"@language":"en","@value":"0.0.1"}],"schema:url":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/dbt_daily_schema","schema:version":[{"@language":"en","@value":"0.0.1"}],"url":"https://raw.githubusercontent.com/ChildMindInstitute/DBT_diary_applet/master/activities/dbt_daily/dbt_daily_schema"}"

**Comment by anq83** [comment]
The above is wrong activity. _id is absent in json-ld

If to compare with normal activity:

![image.png](https://images.zenhubusercontent.com/6316373a3fb7f6df366b544d/fd31ceac-4a0c-451d-a606-7c9dcc0275b7)

**Comment by anq83** [comment]
The login I tried: jeraka1732@wodeda.com 1234567890

The applet id: "applet/6256ff913646a059f4f0600e"

**Comment by anq83** [comment]
@Tom1204   @karser  
Should be investigated on backend side

**Comment by karser** [comment]
I have fixed _id for all activities in "applet/6256ff913646a059f4f0600e".
It is still saying "You currently do not have any applets." and there are no errors.
@anq83  Can you please check what else missing?
![image.png](https://images.zenhubusercontent.com/62e92fe4e7d41a51869b6319/589f5101-b706-496d-a810-5b659d136960)

**Comment by anq83** [comment]
@karser 
at least here're still undefined activities

![image.png](https://images.zenhubusercontent.com/6316373a3fb7f6df366b544d/f39f5ad5-e2f0-455a-a943-7e2346448f8c)

**Comment by anq83** [comment]
@karser 
I can login under this account and see all applets => undefined issue resolved for this account
jeraka1732@wodeda.com 1234567890

**Comment by anq83** [comment]
@karser 
under this one - still have issues
jeligi9407@zneep.com

![image.png](https://images.zenhubusercontent.com/6316373a3fb7f6df366b544d/ee32b176-0b6d-4b67-815f-a95c21d82890)

**Comment by anq83** [comment]
both staging

**Comment by natalia-muzyka** [comment]
Verified as fixed for all the accounts mentioned above.

https:/admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/
ML v0.21.59 staging
iPhone 13 // iOS 15.6
Google Pixel 5a // Android 11

**Comment by natalia-muzyka** [comment]
@karser 
The issue occurred on my prod accounts today:
anita_ml@protonmail.com	qwe123!!!
bruce_ml@protonmail.com	12345678
bernard_ml@protonmail.com	qwe123!!!
demo_test_account@ml.com	123456

ML Pilot v0.21.54 prod

cc: @eleonova-scn

**Comment by natalia-muzyka** [comment]
UPD: the issue is not reproducible anymore on the accounts above

@karser @eleonova-scn
